
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Dec 29 04:33:06 CET 2021
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int READ = 10;
  public static final int PLUS = 12;
  public static final int SEMI = 18;
  public static final int CHAR = 7;
  public static final int IN = 11;
  public static final int LEFTPAR = 14;
  public static final int FILE = 3;
  public static final int RETURN = 19;
  public static final int END = 9;
  public static final int INTCONST = 22;
  public static final int RIGHTPAR = 15;
  public static final int COLON = 16;
  public static final int ID = 21;
  public static final int PROGRAM = 2;
  public static final int DO = 5;
  public static final int BEGIN = 8;
  public static final int STRING = 4;
  public static final int EOF = 0;
  public static final int CHARCONST = 23;
  public static final int MINUS = 13;
  public static final int error = 1;
  public static final int ASSIGN = 17;
  public static final int INTEGER = 6;
  public static final int OPEN = 20;
}

