
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Jan 13 03:52:44 CET 2022
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SEMICOLON = 19;
  public static final int ELSE = 8;
  public static final int INT = 3;
  public static final int EQUAL = 17;
  public static final int NOTEQUAL = 18;
  public static final int LEFTPAR = 11;
  public static final int BOOLEANCONST = 25;
  public static final int INTCONST = 23;
  public static final int RIGHTPAR = 12;
  public static final int IF = 6;
  public static final int COLON = 20;
  public static final int ID = 22;
  public static final int LESSOREQUAL = 14;
  public static final int BOOLEAN = 4;
  public static final int LESSTHAN = 13;
  public static final int EOF = 0;
  public static final int GREATEROREQUAL = 16;
  public static final int REALCONST = 24;
  public static final int LEFTBLOCK = 9;
  public static final int RIGHTBLOCK = 10;
  public static final int MAIN = 2;
  public static final int ELIF = 7;
  public static final int error = 1;
  public static final int ASSIGN = 21;
  public static final int REAL = 5;
  public static final int GREATERTHAN = 15;
}

