
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Dec 16 23:57:23 CET 2021
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SEMICOLON = 21;
  public static final int ELSE = 8;
  public static final int INT = 3;
  public static final int EQUAL = 19;
  public static final int NOTEQUAL = 20;
  public static final int LEFTPAR = 13;
  public static final int RIGHTPAR = 14;
  public static final int IF = 6;
  public static final int COLON = 22;
  public static final int ID = 9;
  public static final int LESSOREQUAL = 16;
  public static final int BOOLEAN = 4;
  public static final int LESSTHAN = 15;
  public static final int EOF = 0;
  public static final int GREATEROREQUAL = 18;
  public static final int LEFTBLOCK = 11;
  public static final int RIGHTBLOCK = 12;
  public static final int MAIN = 2;
  public static final int ELIF = 7;
  public static final int CONST = 10;
  public static final int error = 1;
  public static final int ASSIGN = 23;
  public static final int REAL = 5;
  public static final int GREATERTHAN = 17;
}

